name: Build Simple API service

on:
  release:
    types: [published]
    paths:
      - 'particle41/SimpleTimeService*'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
    - 'particle41/SimpleTimeService*'
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
    - 'master'
    paths:
    - 'particle41/SimpleTimeService*'

jobs:
  build-dockers:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'particle41/SimpleTimeService'
            SERVICE_NAME: 'SimpleTimeService'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: syedsalman3753/kattu/.github/workflows/docker-build-1.yaml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  apply-new-change:
    needs: [ "build-dockers" ]
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: v1.8.5
      - name: Apply new changes
        run: |
          aws ecs update-service \
            --cluster document-processing-app-cluster \
            --service document-processing-app-service \
            --force-new-deployment